## Tuples

Vi ska nu prata om Tuples och förtydliga skillnaden mellan Tuples och Lists.

En Tupel är sorts lista, men som inte går att ändra elemten i efter att du skapat den.

Exempel: listor går att ändra 

In [ ]:
min_lista = ['Sommar', 'Sol', 'Markoolio']
print(min_lista)

min_lista.append('vi har korta shorts')        # lägg till ett element till vår lista
print(min_lista)

min_lista[0] = 'Vinter'                        # re-assigna ett element i vår lista
print(min_lista)


['Sommar', 'Sol', 'Markoolio']
['Sommar', 'Sol', 'Markoolio', 'vi har korta shorts']
['Vinter', 'Sol', 'Markoolio', 'vi har korta shorts']


Låt oss nu skapa en Tuple. En Tuple är precis som listor användbara objekt som det går att "samla" information i. 

In [4]:
min_tuple = ('Sommar', 'Sol', 'Markoolio')     # paranteser används för att beteckna tuples!
print(min_tuple)

('Sommar', 'Sol', 'Markoolio')


Det går väldigt bra att indexera Tuples, precis som ex. listor

In [7]:
print(min_tuple[0])
print(min_tuple[-1])
print(min_tuple[:2])

Sommar
Markoolio
('Sommar', 'Sol')


**Till skillnad mot listor går det INTE att förändra i Tuples efter den väl blivit skapad**

In [9]:
min_tuple.append('Bernard Sanders')        # det går ej att lägga till

AttributeError: 'tuple' object has no attribute 'append'

In [12]:
min_tuple[0] = 'Vinter'                   # det går heller ej att re-assigna element i tuplar

TypeError: 'tuple' object does not support item assignment

**Men**, detta är inte nödvändigtvis dåligt. I många fall vill vi, av säkerhetsskäl, inte att data som skapats ska kunna förändras.

Vi kan addera tuplar om vi vill, och det fungerar på samma sätt som listor

In [13]:
en_tuple = ('Backstreets', 'Back', 'Alright')
annan_tuple = ('If', 'you', 'want', 'to', 'be', 'my')

print(en_tuple)
print(annan_tuple)

('Backstreets', 'Back', 'Alright')
('If', 'you', 'want', 'to', 'be', 'my')


In [14]:
min_tuple + annan_tuple

('Sommar', 'Sol', 'Markoolio', 'If', 'you', 'want', 'to', 'be', 'my')

Lägg dock märke till att respektive underliggande tuple inte förändrats

In [15]:
print(en_tuple)
print(annan_tuple)

('Backstreets', 'Back', 'Alright')
('If', 'you', 'want', 'to', 'be', 'my')


**En till likhet med listor, är att vi kan direktassigna värden till variabler**

In [45]:
i = [5, 1]

print(i)

[5, 1]


In [18]:
i, j = [5, 1]

print(f'i: {i}')
print(f'j: {j}')

i: 5
j: 1


In [24]:
i, j, k = [5, 1, 'Nosheen']

print(f'i: {i}')
print(f'j: {j}')
print(f'k: {k}')


i: 5
j: 1
k: Nosheen


Det är superviktigt att antalet variabler du assignar är lika många som antal element i din lista

In [ ]:
i, j, k = [5, 1]         # fler variabler än element

print(f'i: {i}')
print(f'j: {j}')
print(f'k: {k}')


ValueError: not enough values to unpack (expected 3, got 2)

In [22]:
i, j = [5, 1, 8]         # färre variabler än element

print(f'i: {i}')
print(f'j: {j}')
print(f'k: {k}')


ValueError: too many values to unpack (expected 2)

**Exakt samma sak funkar för Tuples!**

In [25]:
i, j = (2, 3)

print(f'i: {i}')
print(f'j: {j}')


i: 2
j: 3


**Ett VÄLDIGT vanligt scenario där vi ser tuplar på är följande**

In [26]:
foods = ['Ramen', 'Sushi', 'Granola']
prices = [140, 150, 40]

In [28]:
# varför fungerar nedan?

for food, price in zip(foods, prices):

    print(food, price)

Ramen 140
Sushi 150
Granola 40


In [33]:
for combination in zip(foods, prices):

    print(combination)
    #food = combination[0]
    #price = combination[1]

    #print(f'{food} kostar {price} kronor.')

('Ramen', 140)
('Sushi', 150)
('Granola', 40)


Det vi gör nedan (som vi lärt oss tidigare) är alltså att direktassigna två variabler till de olika elementen
ur tupeln som skapas av zip()-funktionen

In [34]:
for food, price in zip(foods, prices):

    print(f'{food} kostar {price} kronor.')

Ramen kostar 140 kronor.
Sushi kostar 150 kronor.
Granola kostar 40 kronor.


zip()-funktionen kan ta emot hur många listor som helst!

In [44]:
foods = ['Ramen', 'Sushi', 'Granola']
prices = [140, 150, 40]
drinks = ['Virgin Colada', 'Mint Margaritha', 'Tequila Sunrise']

In [43]:
for combination in zip(foods, prices, drinks):

    print(combination)

('Ramen', 140, 'Virgin Colada')
('Sushi', 150, 'Mint Margaritha')
('Granola', 40, 'Tequila Sunrise')


In [38]:
for food, price, drink in zip(foods, prices, drinks):

    print(f'A {food} with a {drink} costs {price} kronor in lala-land.')

A Ramen with a Virgin Colada costs 140 kronor in lala-land.
A Sushi with a Mint Margaritha costs 150 kronor in lala-land.
A Granola with a Tequila Sunrise costs 40 kronor in lala-land.


**Obs, ordningen på variabler är superviktig**

Nedan skapar vi ett logiskt fel, pga felaktig ordning i vår variabelassignment

In [ ]:
for price, food, drink in zip(foods, prices, drinks):

    print(f'A {food} with a {drink} costs {price} kronor in lala-land.')

A 140 with a Virgin Colada costs Ramen kronor in lala-land.
A 150 with a Mint Margaritha costs Sushi kronor in lala-land.
A 40 with a Tequila Sunrise costs Granola kronor in lala-land.


## Hur märks detta av i funktioner?

Låt oss bygga en funktion som gör lite roliga saker med en siffra som vi ger till den

In [47]:
# låt oss skapa en funktion som multiplicerar talet vi ger som input, med tio

def rolig_funktion(nummer):

    produkt = nummer*10

    return produkt

In [48]:
output = rolig_funktion(5)

print(output)

50


Låt oss nu utöka funktionaliteten till att istället göra två saker med vår siffra, och returnera bägge resultaten 

In [49]:
# låt funktionen multiplicera vårt tal med 10 resp. 20, och returnera bägge produkter

In [50]:
def roligare_funktion(nummer):

    gånger_tio = nummer*10
    gånger_tjugo = nummer*20

    return gånger_tio, gånger_tjugo

In [51]:
output = roligare_funktion(5)

print(output)

(50, 100)


**Det vi ser är alltså att OM din funktion returnerar FLER än ett objekt, så kommer alla att levereras i en Tuple**

Vi kan då, precis som innan, fånga upp de olika värdena på följande vis

In [54]:
a, b = roligare_funktion(5)

print(f'a: {a}')
print(f'b: {b}')




a: 50
b: 100


Låt oss nu göra detta supertydligt och skapa en funktion som returnerar massvis av värden

In [56]:
def roligaste_funktionen(nummer):

    gånger_tio = nummer*10
    gånger_tjugo = nummer*20
    gånger_trettio = nummer*30

    delat_på_två = nummer/2
    upphöjt_till_två = nummer**2

    return gånger_tio, gånger_tjugo, gånger_trettio, delat_på_två, upphöjt_till_två


In [57]:
output = roligaste_funktionen(5)

print(output)

(50, 100, 150, 2.5, 25)


In [59]:
a, b, c, d, e = roligaste_funktionen(5)

print(f'a: {a}')
print(f'b: {b}')
print(f'c: {c}')
print(f'd: {d}')
print(f'e: {e}')

a: 50
b: 100
c: 150
d: 2.5
e: 25


## Hur märks detta i listkomprehensioner?

In [61]:
snacks = ['chips', 'choklad', 'jordnötter']
prices = [20, 15, 40]

[combination for combination in zip(snacks, prices)]

[('chips', 20), ('choklad', 15), ('jordnötter', 40)]

In [62]:
[f'{snack} kostar {price} kronor.'  for snack, price in zip(snacks, prices)]

['chips kostar 20 kronor.',
 'choklad kostar 15 kronor.',
 'jordnötter kostar 40 kronor.']

**Tivoli :)**

Oj vad kul! Vi är nu vid entrén, och märker att priserna är rätt... godtyckliga.

In [63]:
number_of_persons = [5, 10, 15]   # sällskapsstorlek
price_per_person = [100, 120, 150]   # pris per person, beroende på sällskapstorlek

# vi ser ovan att det blir dyrare per person, ju större sällskap man är

[combination for combination in zip(number_of_persons, price_per_person)]

[(5, 100), (10, 120), (15, 150)]

In [64]:
# nedan beräknar vi totala sällskapspriset

[number*price for number, price in zip(number_of_persons, price_per_person)]

[500, 1200, 2250]

In [65]:
# nedan beräknar vi totala sällskapspriset

# men ofta, när det inte finns risk för förvirring, brukar jag (och många andra) använda i,j,k etc.. som dummy variables

[i*j for i, j in zip(number_of_persons, price_per_person)]

[500, 1200, 2250]

In [67]:
# nedan gör vi en random beräkning, bara för att vi kan!

[(i+j)**2 for i, j in zip(number_of_persons, price_per_person)]

[11025, 16900, 27225]

Låt oss nu definiera en funktion som adderar två värden till varandra, och returnerar summan

In [68]:
def addera(a,b):

    summa = a+b

    return summa

In [70]:
lista_ett = [1, 1, 1]
lista_random = [5, 8, 11]

[addera(i, j) for i, j in zip(lista_ett, lista_random)]

[6, 9, 12]

En sista detalj på det här. Detta är nog inte så överraskande, men vi understryker ändå.

In [71]:
lista_ett = [1,1,1]
lista_random = [5, 8, 11]
lista_tiotal = [10, 20, 30]
lista_nollor = [0, 0, 0]

Precis som tidigare, så måste antalet dummy variables vara lika många som längden av de genererade tuplarna

In [ ]:
# detta blir error, vi har för få dummy variables

[i+j+k for i, j, k in zip(lista_ett, lista_random, lista_tiotal, lista_nollor)]

ValueError: too many values to unpack (expected 3)

In [76]:
[i for i in zip(lista_ett, lista_random, lista_tiotal, lista_nollor)]

[(1, 5, 10, 0), (1, 8, 20, 0), (1, 11, 30, 0)]

In [ ]:
# nedan assignar vi 4 dummy variables, vilket funkar!
# dock använder vi inte alla i våra beräknar (specifikt l)
# men det är HELT OK
# python doesnt care - vad du väljer att göra med variablerna är helt upp till dig

[i+j+k for i, j, k, l in zip(lista_ett, lista_random, lista_tiotal, lista_nollor)]

[16, 29, 42]

## Numpy

Numpy (numerical python) är ett viktigt paket för numeriska beräkningar i Python. Specifikt när man vill jobba med Linjär Algebra. 

In [81]:
lista_1 = [1, 2, 3]
lista_2 = [4, 5, 6]

# listorna konkateneras, inte adderas! Dvs, läggs ihop på bredden.

print(lista_1 + lista_2)

tuple_1 = (1, 2, 3)
tuple_2 = (4, 5, 6)

print(tuple_1 + tuple_2)

# listor och tuplar beter sig likadant vid addition, de konkateneras på bredden

[1, 2, 3, 4, 5, 6]
(1, 2, 3, 4, 5, 6)


In [83]:
# multiplicerar vi en lista eller tupel med ett tal, kommer listan att konketeeras med sig själv, 
# lika många gånger som talet vi multiplicerar med.

print(lista_1*3)
print(tuple_1*3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
(1, 2, 3, 1, 2, 3, 1, 2, 3)


**Nu kör vi med Numpy!**

In [86]:
# numpy är ett standardpaketet, likt ex random, som man enkelt kan importera in direkt

import numpy as np      # det är väldigt vanligt att ge numpy aliaset np vid importering - gör det ni också

vector = np.array([1, 2, 3, 5, 8])    # här skapar vi ett objekt av datatypen "array"

print(vector)
print(type(vector))

[1 2 3 5 8]
<class 'numpy.ndarray'>


Ok, låt oss utforska denna nya datatyp lite grann.

Vi kan indexera numpy arrays precis som tidigare för listor och tuples

In [89]:
print(vector[0])
print(vector[:2])
print(vector[-1])

1
[1 2]
8


En array **ÄR** förändringsbar, precis som en lista - men INTE som tuples.

In [91]:
print(vector)
vector[0] = 20
print(vector)

[1 2 3 5 8]
[20  2  3  5  8]


Om vi multiplicerar en numpy array (eller en vektor) med ett tal, kommer det att ske **elementvis multiplikation**

In [93]:
print(vector)
print(vector*20)
print(vector)

[20  2  3  5  8]
[400  40  60 100 160]
[20  2  3  5  8]


Vad händer om vi adderar numpy arrays till varandra?

In [96]:
vector_one = np.array([1, 1, 1])
vector_random = np.array([2, 4, 9])

# under addition av numpy arrays sker alltså återigen elementvis addition

print(vector_one + vector_random)

# ditto för subtraktion

print(vector_one - vector_random)

[ 3  5 10]
[-1 -3 -8]


---

Det finns många olika sätt att snabbt skapa arrays på. Ett av de är följande

In [98]:
# ones() är en metod till np som skapar en numpy array som består av ett givet antal ettor

ettor = np.ones(5)   # skapar en np array av längd 5 och består enbart av ettor

print(ettor)

[1. 1. 1. 1. 1.]


In [99]:
nollor = np.zeros(5)   # skapar en np array av längd 5 och består enbart av nollor

print(nollor)

[0. 0. 0. 0. 0.]


**Omvandla listor till arrays**

In [100]:
mina_siffror_i_en_lista = [x for x in range(5)]
print(mina_siffror_i_en_lista)

[0, 1, 2, 3, 4]


In [101]:
# för att ändra en lista till en numpy array, använder vi np.array() metoden
# där vi helt enkelt ger vår lista som argument till metoden

mina_siffor_i_en_array = np.array(mina_siffror_i_en_lista)
print(mina_siffor_i_en_array)
print(type(mina_siffor_i_en_array))

[0 1 2 3 4]
<class 'numpy.ndarray'>


Fungerar arrays enbart för siffror.. ?

In [102]:
mina_strängar_i_en_lista = [x for x in 'abc']
print(mina_strängar_i_en_lista)

['a', 'b', 'c']


In [103]:
mina_strängar_i_en_array = np.array(mina_strängar_i_en_lista)
print(mina_strängar_i_en_array)

['a' 'b' 'c']


Svar: Ja, det går att skapa arrays med annat än siffror

**Vad händer om vi försöker lägga ihop arrays som består av av olika datatyper?**

In [104]:
mina_siffor_i_en_array + mina_strängar_i_en_array

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('int64'), dtype('<U1')) -> None

Det går inte, vilket kanske inte är så förvånande.

**Linspace**

linspace är en funktion som fungerar ungefär som range(), och används för att generera en mängd med siffror

In [108]:
# detta är ett till sätt att skapa en array av siffror på 

np.array([x for x in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Ett snyggare, och kanske mer effektivt sätt, är genom att använda linspace()


In [112]:
# följande kod kommer att skapa en array med (by default) 50 stycken siffror mellan 0 och 10 - i lika stora steg

np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [115]:
# genom att ge ett till argument kan vi kontrollera antalet tal som skapas mellan ditt start och ditt stopp
# nedan väljer vi att skapa en array med 5 stycken siffror mellan 0 och 10

np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0, 10 , 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Generellt sett ser det ut på följande sätt

np.linspace(start, stop, num)

där start är din startpunkt, stop är din slutpunkt och num är antalet punkter du vill skapa mellan start och stop, inklusive

In [120]:
meddelande = """BRA JOBBAT

STICK HEM NU :)"""

## Mean & Sum

In [117]:
min_array = np.array([1, 6, 20])
print(min_array)

[ 1  6 20]


In [119]:
print(f'Medelvärdet av min array är {np.mean(min_array)}.')
print(f'Summan av min array är {np.sum(min_array)}.')

Medelvärdet av min array är 9.0.
Summan av min array är 27.


In [121]:
print(meddelande)

BRA JOBBAT

STICK HEM NU :)
