<a href="https://colab.research.google.com/github/aleylani/Python-AI25/blob/main/exercises/solutions/10_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

---
These are introductory exercises in Python with focus in **Numpy**.

<p class = "alert alert-info" role="alert"><b>Remember</b> to use <b>descriptive variable names</b> in order to get readable code </p>

<p class = "alert alert-info" role="alert"><b>Remember</b> to format your answers in a neat way using <b>f-strings</b>

<p class = "alert alert-info" role="alert"><b>Remember</b> to format your input questions in a pedagogical way to guide the user

The number of stars (\*), (\*\*), (\*\*\*) denotes the difficulty level of the task

---

## 1. Dice simulations (*)

Simulations of one die,  

&nbsp; a) Calculate theoretical mean of a dice (six-sided) (*)

&nbsp; b) Now do simulations of

- 10
- 100
- 1000
- 10000
- 100000
- 1000000
- 10000000

number of dices and plot their means. (*)

<details>

<summary>Answer </summary>

a)
```
3.5
```

b)

<img src="../assets/numpy_1b.png" width = 300>

</details>




In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Theoretical mean

theoretical_mean = np.mean([1, 2, 3, 4, 5, 6])

print(f'Theoretical mean of a fair six-sided die: {theoretical_mean}.')

# Step 2: Simulations for different number of dice
num_dice = [10, 100, 1000, 10000, 100000, 1000000, 10000000]
simulated_means = []

for n in num_dice:

    rolls = np.random.randint(1,7,size=n)      # simulate n rolls
    mean_roll = np.mean(rolls)                 # calculate the mean of n rolls
    simulated_means.append(mean_roll)
    print(f'Mean for {n} dice rolls: {mean_roll}')

plt.plot(simulated_means)
plt.xticks([0,1,2,3,4,5,6], num_dice)
plt.title('Experimental dice roll means')
plt.xlabel('Dice rolls')
plt.ylabel('Mean roll')
plt.ylim(2.5, 5)                              # bra metod för att kontroller y-axeln
plt.show()
    

---
## 2. Several dices (**)

&nbsp; a) Make a sample space for the sum of two dices, i.e. all possible outcomes of these dices. (*)

&nbsp; b) Count the number of each values in the sample space (*)

&nbsp; c) Now calculate the frequency $f_i$ for each unique value. Also check that the sum of frequencies sums to 1, i.e. $\sum_i f_i = 1$. (*)

&nbsp; d) Make a bar chart of the sum of two dices, with frequencies in y and unique values in x. This is a probability distribution of the sum of your two dices. (*)

&nbsp; e) Now make barplots in subplots of sum of dices for 1 dice, 2 dices, 3 dices and 4 dices. What is the pattern that you see? (**)

<details>

<summary>Hint</summary>

a)

Here are some potentially useful methods:

```py

np.meshgrid(), np.add.reduce(), np.unique()

```

c)

Divide by the total number of outcomes


</details>

<details>

<summary>Answer</summary>


a)

Sample space

```
[[ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]
 [ 6  7  8  9 10 11]
 [ 7  8  9 10 11 12]]
```

b)

Unique values:
```
[ 2  3  4  5  6  7  8  9 10 11 12]
```

Count:
```
[1 2 3 4 5 6 5 4 3 2 1]
```

c)

```
[0.028 0.056 0.083 0.111 0.139 0.167 0.139 0.111 0.083 0.056 0.028]
```

d)


<img src="../assets/numpy2d.png" width = 300>


e)

<img src="../assets/numpy2e.png" width = 500>


We see that when we sum several uniformly distributed random variables we will approach the normal distribution. This is called the central limit theorem, which we will come back to in the statistics course.

</details>

## Elevlösning (Balder) nedan!

In [ ]:
dice_1 = [1,2,3,4,5,6]
dice_2 = [1,2,3,4,5,6]
dice_space_old = []

for roll1 in dice_1:
    for roll2 in dice_2:
        summa = roll1 + roll2
        dice_space_old.append(summa)


print(dice_space_old)

In [ ]:
dice = np.arange(1,7)                       #En tärning
d1, d2 = np.meshgrid(dice, dice)            #2 tärningar
dice_space_flatten = (d1 + d2).flatten()    #Till en lista

print(dice)
print(d1)
print(d2)
print(d1 + d2)
print(dice_space_flatten)

In [ ]:
# 3 och 4 tärningar

dice_3d_1, dice_3d_2, dice_3d_3 = np.meshgrid(dice, dice, dice)                      #3 Tärningar
dice_3d_space = (dice_3d_1 + dice_3d_2 + dice_3d_3).flatten()

dice_4d_1, dice_4d_2, dice_4d_3, dice_4d_4  = np.meshgrid(dice, dice, dice, dice)    #4 Tärningar
dice_4d_space = (dice_4d_1 + dice_4d_2 + dice_4d_3 + dice_4d_4).flatten()

In [ ]:
# Räkna tärningar till dictionary

from collections import Counter

counted_2d = Counter(dice_space_flatten)

print(counted_2d)

for key, value in counted_2d.items():
    print(f"{key}: {value}")

In [ ]:
counted_1d = Counter(dice)
counted_3d = Counter(dice_3d_space)
counted_4d = Counter(dice_4d_space)

In [ ]:
frekvens_count_2d = {key: value / sum(counted_2d.values()) for key, value in counted_2d.items()}

for key, value in frekvens_count_2d.items():
    print(f"{key}: {value}")

summa = 0

for value in frekvens_count_2d.values():
    summa += value

print(summa)

In [ ]:
frekvens_count_1d = {key: value / sum(counted_1d.values()) for key, value in counted_1d.items()}
frekvens_count_3d = {key: value / sum(counted_3d.values()) for key, value in counted_3d.items()}
frekvens_count_4d = {key: value / sum(counted_4d.values()) for key, value in counted_4d.items()}

In [ ]:
x_2d = list(frekvens_count_2d.keys())
y_2d = [y * 100 for y in frekvens_count_2d.values()]

plt.bar(x_2d, y_2d)
plt.title("Frequencies of unique dice amounts")
plt.xlabel("Unique amounts")
plt.ylabel("Frequencies")
plt.yticks(y_2d, [f"{round(y, 1)}%" for y in y_2d])
plt.xticks(x_2d, [str(x) for x in x_2d])
plt.show()

In [ ]:
x_1d = list(frekvens_count_1d.keys())
y_1d = [y * 100 for y in frekvens_count_1d.values()]

x_3d = list(frekvens_count_3d.keys())
y_3d = [y * 100 for y in frekvens_count_3d.values()]

x_4d = list(frekvens_count_4d.keys())
y_4d = [y * 100 for y in frekvens_count_4d.values()]


In [ ]:
fig, axs = plt.subplots(2, 2, figsize=(18, 12))                   # Subplottens hela Canvas

axs[0, 0].bar(x_1d, y_1d)
axs[0, 0].set_title("Möjliga summor med: 1 tärning")
axs[0, 0].set_ylabel("Sannolikhet")
axs[0, 0].set_xticks(x_1d, [str(x) for x in x_1d])
axs[0, 0].set_yticks(y_1d, [f"{round(y, 1)}%" for y in y_1d])

axs[0, 1].bar(x_2d, y_2d)
axs[0, 1].set_title("2 tärningar")
axs[0, 1].set_xticks(x_2d, [str(x) for x in x_2d])
axs[0, 1].set_yticks(y_2d, [f"{round(y, 1)}%" for y in y_2d])

axs[1, 0].bar(x_3d, y_3d)
axs[1, 0].set_title("3 tärningar")
axs[1, 0].set_xticks(x_3d, [str(x) for x in x_3d])
axs[1, 0].set_yticks(y_3d, [f"{round(y, 1)}%" for y in y_3d])

axs[1, 1].bar(x_4d, y_4d)
axs[1, 1].set_title("4 tärningar")
axs[1, 1].set_xticks(x_4d, [str(x) for x in x_4d])
axs[1, 1].set_yticks(y_4d, [f"{round(y, 1)}%" for y in y_4d])

axs[0,0].bar(x_1d, y_1d, color='skyblue')
axs[0,1].bar(x_2d, y_2d, color='orange')
axs[1,0].bar(x_3d, y_3d, color='green')
axs[1,1].bar(x_4d, y_4d, color='red')

fig.tight_layout(pad=1.5)
plt.show()